/**
 * RUBIMED PSE — Chavita & Emvita Descriptions
 * Source: Rubimed Manual — Dr. Michael Kessler, D.C.
 * These descriptions are LOCKED — the AI must never generate its own.
 * Standard dosage: 2× daily 12 drops directly on tongue (adults); children: 2× daily 6 drops.
 */

// ── CHAVITA (Chakra Remedies 1–7) ──────────────────────────────────────────

export const CHAVITA_DESCRIPTIONS = {
  1: {
    chakra: 'Root Chakra — I Am',
    theme: 'Grounding, Vitality, Basic Trust',
    description: 'Chavita 1 is the remedy for the first or root chakra. This chakra is situated in the pelvic region and is associated with the ovaries and testes and regulates the autonomic functions of the pelvic organs. The energetic function is to be rooted and grounded and provides vitality. It also involves basic (primal) trust and self-esteem. Chakra 1 governs the following organs: the ovaries, testes/gonads, bladder, prostate, uterus, lower back (coccyx), and the hips to the feet, the skin, bones and blood. Energetic disturbances in this region relate to the feeling of "I am not good enough" and manifests as a lack of self confidence, self identity, self respect and/or self love. There can be a feeling of not being rooted or grounded, not being connected to the physical body, and lacking deep inherent trust in life (primal trust). When chakra 1 is balanced, a person feels desired, loved and accepted, and stands strong on their own two feet. Self confidence is improved. One feels more peaceful, grounded, prosperous and trusting.',
    conflicts: [1, 2, 3, 4],
  },
  2: {
    chakra: 'Sacral Chakra — I Feel',
    theme: 'Strength, Courage, Stress Resilience',
    description: 'Chavita 2 is the remedy for the second or sacral chakra. This chakra is situated in the lower abdomen below the navel and is associated with the adrenal glands and regulation of the autonomic function. The energetic function is to create and sustain balance, especially during stressful situations. Chakra 2 governs the following organs: the adrenals, kidneys, large intestines, and lower back (sacrum). This chakra also regulates water metabolism, adrenal hormones (adrenaline and cortisol), maintenance of mineral reserves, toxin excretion and functions with respect to behavior during stress (fight or flight response). Energetic disturbance in this region relate to issues of strength and courage, or the strength one pretends to have. There may be a tendency to be self-critical, take care of others before oneself and push and push until one is worn out, leading to collapse. When chakra 2 is balanced, one develops strength courage, harmony and stability in life, especially in times of stress. One feels more emotionally intelligent, allows healthy pleasure in life, is able to accept change and is more relaxed and creative.',
    conflicts: [5, 6, 7],
  },
  3: {
    chakra: 'Solar Plexus Chakra — I Can',
    theme: 'Digestion, Satiation, Self-Esteem',
    description: 'Chavita 3 is the remedy for the third chakra or the solar plexus. This chakra is situated in the upper abdomen, is associated with the pancreas and regulates the autonomic functions related to digestion. The energetic function represents processing feelings and events that one has to digest (both physically and emotionally): absorption (take in), assimilation (process) and excretion (let go). Chakra 3 governs the following organs: the organs of the digestive system including the stomach, pancreas, small intestines, liver, gallbladder and the lumbar spine. Energetic disturbances in this region relate to difficulty digesting and processing the world, which can encompass cravings, addiction, poor digestion, allergies and food intolerances. Fear of loneliness, insecurity and low self-esteem may prevail. There may be a tendency for irritation, anger and aggression. When chakra 3 is balanced, one has a better ability to digest, process and let go of all types of experiences they encounter. One is more confident, reliable, responsible and feels improved self-esteem and self-respect.',
    conflicts: [8, 9, 10, 11],
  },
  4: {
    chakra: 'Heart Chakra — I Love',
    theme: 'Trust, Love, Emotional Healing',
    description: 'Chavita 4 is the remedy for the fourth or heart chakra. This chakra is situated in the region of the heart, is associated with the thymus gland and regulates the immune system function in addition to the heart, lungs and circulation. The energetic function is related to trust and opening the heart to love: developing trust in self, trust in others, trust in life, and loving oneself, loving others, and loving life. Chakra 4 governs the following organs: the heart, lungs, bronchi, thymus gland, breasts, thoracic spine, shoulders and arms down to the fingers. This chakra also deals with the immune system and allergies. Energetic disturbances in this region relate to a lack of trust in oneself, in others and in what life hands us. It can also be related to issues of love and connections to self and others and may be expressed as being hard on oneself or hard on others. Feelings of lack of control, being trapped, unfulfillment, jealousy, self-sacrifice, lack of self worth, depression and isolation may be experienced. When chakra 4 is balanced, one learns to trust, is more open to love and is able to develop deeper connections with oneself and others. One practices forgiveness and compassion and has great ability for self-control and self-acceptance. Confidence and faith increase and one is more peaceful, generous and strong.',
    conflicts: [12, 13, 14, 15, 16],
  },
  5: {
    chakra: 'Throat Chakra — I Speak, I Hear the Truth',
    theme: 'Communication, Expression, Truth',
    description: 'Chavita 5 is the remedy for the fifth or throat chakra. This chakra is situated in the throat region and is associated with the thyroid gland and regulates metabolic functions within the body. The energetic function is related to communication, expressing ourselves to the outside world, expressing our truth and voicing our opinion. Chakra 5 governs the following organs: the thyroid gland, neck, vocal cords, tonsils, teeth, lower jaw, larynx, and cervical spine. This chakra also deals with metabolic functions, as the thyroid is the master gland of metabolism. Energetic disturbances in this region relate to communication, with difficulty in being heard and in expressing oneself properly. It can be observed through a shy, anxious, weak voiced individual who seems indecisive and afraid to speak or an individual who is self righteous with a dominating voice and exhibits excessive talking without the ability to listen. One may feel invisible, have had exposure to criticism, have feelings of unworthiness, and swallow emotions. When chakra 5 is balanced, one has the ability to communicate: the ability to speak, to listen and to understand what others mean. A resonant voice and emotional honesty is more prevalent. A confidence develops in one\'s expression to the outside world, where one can comfortably express their opinion, knowledge and beliefs to others.',
    conflicts: [17, 18],
  },
  6: {
    chakra: 'Third Eye Chakra — I See',
    theme: 'Harmony, Balance, Intuition',
    description: 'Chavita 6 is the remedy for the sixth chakra or the third eye. This chakra is situated between the eyebrows, is associated with the pituitary gland and regulates the hormonal functions within the body. The energetic function is to create harmony and balance in one\'s life. Chakra 6 governs the following organs: the organs of the head including the pituitary eyes, ears, nose, mouth, sinuses, and upper jaw. This chakra also deals with all hormonal and endocrine issues, as the pituitary is the master gland and conductor of all endocrine organs. Energetic disturbances in this region relate to lack of harmony with oneself and others, not being able to establish one\'s own identity and disconnection from one\'s intuition. It can be expressed as stress felt due to all the different roles one is obligated to fulfill in life (family, work, social relationships and responsibilities). It may present as tension, stress, restlessness, hyperactivity, the need to always be doing something or workaholic tendencies, lack of concentration and forgetfulness. When chakra 6 is balanced, one has an understanding of all influences from the outside, integrates them into daily life and adapts the body to all duties and relationships it faces. Essentially one will have all the different parts of their life working in harmony and find better balance between working and relaxing. Creativity and better memory are more prevalent. One is more in touch with their intuition.',
    conflicts: [19, 20, 21, 22, 23, 24],
  },
  7: {
    chakra: 'Crown Chakra — I Know',
    theme: 'Structure, Order, Spiritual Integration',
    description: 'Chavita 7 is the remedy for the seventh or crown chakra. This chakra is situated at the crown (top) of the head, and is associated with the hypothalamus and the epiphysis, and regulates neuroendocrine secretions, circadian rhythms and homeostasis. The energetic function is to impart structure, regulation and order to the entire system including cyclical functions and the sleep-wake cycle. Chakra 7 governs the following organs: the organs in the upper region of the head including the hypothalamus and pineal gland, the brain and all associated functions. Energetic disturbances in this region relate to a person\'s stance in the environment and a sense of imbalance in the greater whole of life. One who has lost the ability to listen to their inner voice may find that this has lead to a strict belief system and disconnection from the body, confusion, or a dominating personality. When chakra 7 is balanced, one is connected to the sense of balance within the framework of life (structure, rules and order) and allows for awareness, openness, intelligence, perspective and trust. Overcoming boundaries of the ego expands growth possibilities to further personality development, enables greater spiritual knowledge and brings a deeper meaning to life.',
    conflicts: [25, 26, 27, 28],
  },
};

// ── EMVITA (Conflict Remedies 1–28) ────────────────────────────────────────

export const EMVITA_DESCRIPTIONS = {
  1: {
    name: 'Low Self-Esteem',
    subtitle: 'Chakra 1 — Root Chakra Conflict',
    description: 'Emotional issues addressed: You experience feelings of not being good enough, worthlessness, inferiority, or low self-esteem. You lack confidence and may have identity issues. You feel that you do not have the inner strength to deal with the burdens in life. You may be exploited or feel like a victim. You feel you have to struggle more than others, yet still are not good enough. This conflict can be due to early childhood trauma caused by divorce, death of a parent, neglect, being an undesired child, in utero or birthing trauma, abandonment, physical or mental abuse, injury to coccyx, or not feeling safe, secure or loved. Guidance: Acknowledge your own potential and strength. Positive Affirmation: I have the strength, talents and skills to confidently fulfill and enjoy my tasks in life.',
  },
  2: {
    name: 'Difficult Concentration',
    subtitle: 'Chakra 1 — Root Chakra Conflict',
    description: 'Emotional issues addressed: You experience difficulty with focusing and concentration, can easily be distracted or get lost in thought. You may live life halfheartedly with a lack of conviction and have a tendency to postpone or avoid things. You do not feel grounded, without firm roots or like a leaf blowing in the wind. You haven\'t realized your full potential, your place in life, your destiny or your purpose. You would rather be somewhere else (another family, another workplace, another country). You may withdraw in stressful situations. This conflict can be due to growing up in a dominating family where you were not given the opportunity to develop as your own person or experienced an uprooting event (i.e. a move to a new country, death of a loved one). Guidance: Accept your place in the world. Realize and tap into your own strength, using it resourcefully. Positive Affirmation: I direct my energy toward my life goals and I am successful.',
  },
  3: {
    name: 'Overwhelm and Loss of Control',
    subtitle: 'Chakra 1 — Root Chakra Conflict',
    description: 'Emotional issues addressed: You feel overwhelmed; not strong enough to cope with life\'s challenges. You hide your strengths from the world and live life as a never ending struggle. You experience indecision and tend towards postponing things or procrastination. You have feelings of helplessness, loss of control, or being stuck in certain circumstances. You feel dependent on others. You lack willpower, cannot face life\'s challenges and feel incapable of making changes for the better. You may hide behind a mask of managing and toughness. This conflict can be due to never being allowed to be yourself and always relying on others. Past experience has shown that using your own talents and strengths leads to punishment and you have lost your confidence. Life circumstances have put too much on your plate, and you do not feel like you are in control of the outcome. Guidance: Develop the feeling that your life is fulfilled by your own strengths. Be confident, see yourself for who you are, stand on your own two feet, confidently express your own opinion and point of view, and stand up resolutely for your convictions. Positive Affirmation: I am firmly and confidently rooted in life and I positively grow with each new day.',
  },
  4: {
    name: 'Extreme Self-Control',
    subtitle: 'Chakra 1 — Root Chakra Conflict',
    description: 'Emotional issues addressed: You are hard on yourself and have high expectations for yourself and others. You conduct your life in a very controlled fashion. You present an appearance of being calm, balanced and in control; however, this is a facade as you don\'t want to show your true feelings to others. You may appear emotionless or indifferent and have trouble expressing your feelings. There is a tendency to suppress your emotions or override them with tasks that need to be fulfilled. This conflict can be due to strict discipline or submissiveness at an early age, or taking on the role of "being the adult" as a child. Strict self control of emotions can result from not wanting to feel or care, as this leads to being hurt. Guidance: Be unconditionally loving and accepting of yourself, no matter what and with no strings attached. Learn to be comfortable openly expressing your feelings, opinions and wishes. Allow yourself to live the life you want. Positive Affirmation: I love and care for myself, my body and my emotions.',
  },
  5: {
    name: 'Hectic and Nervous Feelings',
    subtitle: 'Chakra 2 — Sacral Chakra Conflict',
    description: 'Emotional issues addressed: You have excess nervous energy that can make you feel restless, excitable or tense. You may feel "butterflies in the stomach" or like a "live humming wire". You always need to be busy and find it hard to relax and let go or alternatively, you are so tired yet unable to "turn off" and fall asleep. You find yourself often in a hurry and always under stress. The stress can manifest as physical symptoms including high blood pressure, low back pain, intestinal problems, stomach aches, diarrhea, constipation, and kidney disease. You may appear calm on the outside with the need to release built-up pressure. This conflict can be due to neglect, denial of feelings, abuse or wanting to achieve in order to be recognized and accepted by others. There is a deep internal belief that if you are not in constant motion and alert, you will lose control. Guidance: Relax, slow down, and take a deep breath. Derive peace and strength from calmness and learn to live life instead of the illusion of life. Be happy with yourself and your abilities, even if everything does not work to perfection. Positive Affirmation: I am relaxed, calm and secure in the knowledge that everything is perfect.',
  },
  6: {
    name: 'Perseverance and Somatized Fears',
    subtitle: 'Chakra 2 — Sacral Chakra Conflict',
    description: 'Emotional issues addressed: You appear calm and controlled on the outside, but are full of worry, anxiety or apprehension on the inside. You may not be aware of anxious feelings, as you want to feel mentally strong. Tension, anxiety, worry or fear is deposited into the body\'s cells and organs (somatized fears), creating physical symptoms (i.e. low back pain, diarrhea). You experience chronic mental and physical overexertion yet continue to push past your own boundaries and have a hard time saying no. This conflict can be due to neglect, denial of feelings or abuse. There is a feeling or belief that in order to be loved and accepted one must perform his/her duties while remaining strong, despite being overtaxed with no time for relaxation. Guidance: Develop the ability to recognize and acknowledge your limits and give yourself permission for times of rest and relaxation. Listen to your body, learn to say no and work to overcome your inner anxiety. Positive Affirmation: My body has its own inner wisdom and I am secure within.',
  },
  7: {
    name: 'Show of Strength',
    subtitle: 'Chakra 2 — Sacral Chakra Conflict',
    description: 'Emotional issues addressed: You appear strong and in control on the outside, but feel weak, tired or vulnerable on the inside. You lack inner peace. You hide behind false self confidence, which may be seen as arrogance or defiance. Despite feelings of weakness, you continue to push on resulting in a tendency to exert yourself until you drop. You often exceed your own limits. This conflict can be due to neglect, denial of feelings or abuse. Circumstances in life have lead for the need to pretend to have more strength than one feels they actually have, and to hide their weaknesses and symptoms (including adrenal burnout). Guidance: Realize your own strengths, talents and potential, while at the same time, acknowledge and accept your true self and your areas of weakness. Modesty, sincerity and truthfulness are an expression of genuine strength. Positive Affirmation: I am my true self. I am strong inside and out and can handle all situations.',
  },
  8: {
    name: 'Isolation',
    subtitle: 'Chakra 3 — Solar Plexus Conflict',
    description: 'Emotional issues addressed: You desire connections and relationships but have difficulty opening up and approaching others. You feel alone, not part of the group and not understood. You may have had a circumstance in life that makes you feel different from everyone else. You hesitate to embrace life and may isolate yourself from others and/or life. Feelings of isolation lead to unhappiness, indifference, lethargy, and inactiveness. This conflict can be due to too much or too little responsibility, fear of punishment or emotional manipulation. This can arise from immigration, isolation within a family or circumstances that isolates you from the group (i.e., illness, death, etc.) and makes you feel different than everybody else. Guidance: You have the right to live life to the fullest in any situation and deserve happiness and fulfillment. Embrace your individuality, trust you are not alone, and go take a bite out of life. Positive Affirmation: I know that I am a part of the whole, am deeply fulfilled and enjoy life with all my senses.',
  },
  9: {
    name: 'Pent-up Emotions',
    subtitle: 'Chakra 3 — Solar Plexus Conflict',
    description: 'Emotional issues addressed: You suppress and/or bottle up your emotions. You may have the tendency to get frustrated, irritated or angry very quickly, especially if things don\'t go the way you want. You get stuck in anger instead of digesting the experience and moving on. You try to control your emotions but may find you "lose it" instead. You try to act calmly, nicely and politely to others, even if someone hurts your feelings (silent sufferer). You tend to satisfy the needs of others and not have your own wishes fulfilled. This conflict can be due to too much or too little responsibility, fear of punishment, emotional manipulation, fulfilling the wishes of others, and not being given the opportunity to express emotions. Negative emotions are suppressed in order to be loved and appreciated. Guidance: Learn to digest the experience and move on rather than get stuck in anger. Recognize your limits and learn to say no, trusting that it doesn\'t lead to rejection. Positive Affirmation: I communicate my feelings clearly and confidently with understanding and compassion.',
  },
  10: {
    name: 'Discontent and Wanting More',
    subtitle: 'Chakra 3 — Solar Plexus Conflict',
    description: 'Emotional issues addressed: You have a persistent feeling of dissatisfaction, frustration and a hunger for more. You may feel that you are not getting your share in life. You are not satisfied with what you have, it is never enough. In order to be happy, you expect more out of life: you may yearn for more knowledge, wisdom, depth, wealth, power, possessions, fun and the good things in life. This conflict can be due to loss of possessions, loss of relationships, unstable emotions or deprived affection from others, too much or too little responsibility, or your will was taken away. Often, one tries to fill the void (hunger) with good feelings through emotional eating, workaholism, addictions (tobacco, alcohol, drugs, food, sex), etc. Guidance: Be content and thankful for what you have in life, realizing that what you already have is more than enough. Find inner happiness without needing to add more people or objects. Positive Affirmation: I love myself and accept my abundance unconditionally.',
  },
  11: {
    name: 'Hunger for Good Feelings',
    subtitle: 'Chakra 3 — Solar Plexus Conflict',
    description: 'Emotional issues addressed: You feel an inner dissatisfaction, deep discontent, or frustration. You crave good feelings. You want to be cared for, to feel that somebody loves you. You have feelings of unrest and restlessness, as you are always searching for something to fill the emotional hunger. You may feel cheated out of a sense of well-being and need to protect your boundaries and the nice things that bring you joy. This conflict can be due to an unstable emotional environment or being starved for affection from others, loss of relationships, too much or too little responsibility, or your will was taken away. There may be a tendency for dependency, addictions and eating disorders (anorexia and/or bulimia). Guidance: Recognize your own needs and nurture yourself emotionally. Realize that true happiness can only come from within, not from what others give you. To find the love you seek, you must first find the love within yourself. Positive Affirmation: I love and nourish myself and open my heart to allow all my needs to be met.',
  },
  12: {
    name: 'Mental Overexertion',
    subtitle: 'Chakra 4 — Heart Chakra Conflict',
    description: 'Emotional issues addressed: You have difficulty trusting others and possibly even yourself. You may have the tendency to over think things and try to analyze what others say or mean. You feel mentally overtaxed, exhausted, or overwhelmed and under pressure for all you have to do. It might be difficult to concentrate and there may be internal feelings of wanting to escape. You try to keep your emotions under control and tend to be more rational than emotional. This conflict can be due to abandonment, rejection, death, divorce, grief, or betrayal. A broken trust has lead to over analyzing the intention of others and the need to feel in control. The feeling of lack of control is expressed through the attempt to control one\'s emotions, plan things, or potentially try to control everything going on around them. Guidance: You need to develop trust in life and go with the flow without needing to have everything under control. You do not need to plan for everything. Being human is about being emotional. Positive Affirmation: I confidently trust that all is perfect, just as it is.',
  },
  13: {
    name: 'Deeply Injured and Withdrawn',
    subtitle: 'Chakra 4 — Heart Chakra Conflict',
    description: 'Emotional issues addressed: You have been deeply hurt or betrayed so you withdraw and build up walls to protect yourself. You have the tendency to distance yourself from others and may feel indifferent or misunderstood. You focus on tasks, family or work rather than emotions. You don\'t feel like you can cope with another disappointment. You lack faith and trust in yourself and/or in others. This conflict can be due to abandonment, rejection, death, divorce, grief, or betrayal. A broken trust or heartbreak has lead to a deep sense of betrayal and lack of faith in overcoming the hurt, with fear that it could happen again. Guidance: You need to trust that not everyone is out to hurt you and that your interpretation may be filtered through personal context. Learn to open up emotionally, make your peace and re-establish contact with others. Positive Affirmation: I live life confidently, with trust and an open mind.',
  },
  14: {
    name: 'Introverted',
    subtitle: 'Chakra 4 — Heart Chakra Conflict',
    description: 'Emotional issues addressed: You have been deeply hurt or betrayed and retreat emotionally leading to the feeling of being trapped or shut in with no way out. You may be distrustful, timid or anxious. You feel under pressure due to the expectations of others. You feel tense and tight, like you cannot breathe deeply and freely. You have the tendency to isolate yourself from the world around you. This conflict can be due to abandonment, rejection, death, divorce, grief, betrayal, or severe emotional trauma. The emotional protective mechanism of retreat and withdrawal has lead to a feeling of being trapped and the physical symptoms associated with that include anxiety, fear, tension, compulsions, difficulty breathing or claustrophobia. Guidance: Recognize that fear is the source of isolation, and that it is safe to open up emotionally again. Positive Affirmation: The obstacles I face are growth incentives and I keep my eyes and ears open for new growth opportunities.',
  },
  15: {
    name: 'Apprehensive',
    subtitle: 'Chakra 4 — Heart Chakra Conflict',
    description: 'Emotional issues addressed: You were deeply hurt and still have not overcome it, fearing that it could happen again. Anxiety, fear and worry weigh on your heart and block you from fully enjoying life. You may feel abandoned or all alone without support. You may have developed other fears (spiders, mice, rejection, relationships, a broken heart, etc.) and go about life cautiously or without taking initiative. This conflict can be due to abandonment, rejection, death, divorce, grief, betrayal, a broken heart, or severe emotional trauma. The emotional protective mechanism of retreat and withdrawal has lead to feeling alone, great sorrow, grief, anxiety, fears and phobias. Guidance: Understand that fear creates fear and blocks the flow of energy. You need to develop trust that others and life are not out to actively hurt you and, with time, the emotional pain will heal. Positive Affirmation: I know that fear and worry are part of life and will use them as tools for opportunities of growth.',
  },
  16: {
    name: 'Panic',
    subtitle: 'Chakra 4 — Heart Chakra Conflict',
    description: 'Emotional issues addressed: You have been deeply hurt and it seems hard to believe that you will ever be able to fully trust or feel completely happy again. You may tend to anticipate things going badly. You experience anxiety or panic, but mask them with an attitude of braveness and ambition. The panic can be a true panic attack or negative thoughts that produce brief fear that you have become accustomed to. A fear of failure can make you highly competitive. This conflict can be due to abandonment, rejection, death, divorce, grief, betrayal, a broken heart, severe emotional trauma, or a panic-inducing experience. An emotional experience has lead to anxiety and/or panic attacks, fears and phobias. Such feelings like fear of dying and feelings of paralysis cannot be resisted. Fears can build up in huge proportions in one\'s imagination. Guidance: Life always goes on, even after the worst situations. Since fears block the flow of energy you should develop and strengthen your basic trust in the positive and tranquil aspects of life. Positive Affirmation: I listen to my heart and listen to the voice of love, light and clarity.',
  },
  17: {
    name: 'Emotional Emptiness',
    subtitle: 'Chakra 5 — Throat Chakra Conflict',
    description: 'Emotional issues addressed: You have difficulty expressing yourself and often swallow your feelings. You have experienced a trauma or shock that you haven\'t recovered from, leaving you emotionally empty. You may appear indifferent or have no feelings, as little emotion is expressed. You can present a calm, controlled and rational exterior where nothing seems to affect you. You are not able to express the depths of how you feel and ultimately don\'t speak your truth. This conflict is related to communication and can be due to a great trauma or shock that you haven\'t recovered from. You may have been exposed to lies, emotional abuse, secrets, criticism, death of a loved one, or in a drug dependent family. Guidance: Free your suppressed emotions to reharmonize your heart and your mind. Notice what you are prone to swallow or suppress, and then actively express these emotions and feelings. This will allow you to be more authentic, straightforward, and learn to say what you really mean. Positive Affirmation: I feel alive and am open to express my emotions.',
  },
  18: {
    name: 'Difficulty Expressing and Hasty',
    subtitle: 'Chakra 5 — Throat Chakra Conflict',
    description: 'Emotional issues addressed: You have trouble expressing your opinion or communicating clearly in order to be understood. You don\'t express how you feel and ultimately don\'t speak your truth. Your mind works faster than your actions/words, so you have too many thoughts or impulses which make you appear disorganized, hasty, impulsive, confused or restless. You may feel misunderstood, ignored or a victim of circumstance. You may be a silent sufferer or very talkative, either way you do not feel heard and are not able to express what is really important to you. This conflict is related to communication and can be due to growing up in a dominating family, in a "children should be seen and not heard" environment, or not given the opportunity to express oneself or one\'s opinion. One may stutter due to a rush of too many thoughts. Guidance: In silence is strength should become your new theme. Relaxed, calm and slow breathing is the gateway to inner balance. Slow all actions and thoughts down to move forward with full confidence. Positive Affirmation: I calmly give my inner voice room to express itself and I will listen.',
  },
  19: {
    name: 'Indecisive',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: You have trouble making decisions; this indecisiveness is rooted in fear of making a mistake or missing out on a better opportunity. You try to take everyone and everything into consideration before you take action, which can lead to doing nothing. You try to be pleasing, accommodating and avoid confrontation, with a "don\'t rock the boat attitude". You search for peace, harmony and balance within and may appear shy or withdrawn. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, being told one thing and seeing another, or denial of intuition. You may have had to adopt a diplomatic attitude to keep the peace but in turn suppressed your own wishes and desires. Guidance: Find strength in taking a definitive stance, especially in making clear and firm decisions that tend to be difficult. You should resolutely work on your own plans and not worry about the reactions of others. Positive Affirmation: I have a sense of what is best for me and confidently put this into action.',
  },
  20: {
    name: 'Self Sufficient',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: You are self sufficient. You may be perceived as proud, self-involved and hard to approach or on the other hand, shy and reserved. You have difficulty asking for help and find solutions to your problems on your own. You may think you can do it better and more efficiently and so would rather do it yourself. This leads to being overwhelmed with the amount of work you have to do. Isolation may come with the self sufficiency and with deep feelings of being unloved and disliked. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, or being told one thing and seeing another. One may lack emotional intelligence and get wrapped up in their own stuff, failing to recognize others\' concerns or issues. Guidance: Learn to love yourself, exercise social confidence, and realize it is okay to ask for help when needed. Positive Affirmation: I gladly reach out to others, as they enrich and complete my life.',
  },
  21: {
    name: 'Physical Overexertion',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: You are driven, ambitious and always on the go, with the internal feeling of needing to be doing or accomplishing something. You may be seen as a workaholic, hyperactive or irritable. You are physically overtaxed and push past your own boundaries to fulfill your goals. You are unable to relax with the potential to burn out, as there always seems to be so much to do. You hope someone recognizes you for all the effort but are often disappointed since through hurrying you neglect your own needs and perhaps the needs of others. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, or being told one thing and seeing another. Nail biting, hair pulling, lip biting, headaches or back pain may be signs of enormous pressure and tension and warning signals of overstrain in the body. Guidance: Learn to recognize your own boundaries and how much you can truly handle. Respect these limits. Make time for rest and relaxation. Positive Affirmation: I know my strengths and respect my limits, so that my body and mind remain in harmony.',
  },
  22: {
    name: 'Mental Restlessness',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: Your mind is constantly active. You think about your obligations and it seems that your thoughts never take a break. A thousand thoughts whirl around in your mind. You have difficulty relaxing. You may experience tension, inner restlessness, worries, crowded thoughts, absentmindedness or mental nervousness. There may be deep feelings of dissatisfaction and underlying fears of loss of power or of missing something. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, or denial of intuition. Mental over activity and worries may enter dreams and be the reason behind sleep disorders. It may also be expressed as tension headaches, migraines, obsessive thinking, anxiety, neck tension, tinnitus, nervousness, lack of concentration and irritability. Guidance: Tranquility is strength. You need to make time for relaxation and let go of some of your tasks and worries. Find the courage to get more deeply involved with experiences and feelings without anticipating disappointment. Positive Affirmation: I remain calm, balanced and centered, and live to my full potential.',
  },
  23: {
    name: 'Tense',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: You are trapped in tension and unable to relax physically or mentally. Despite being exhausted you still go on. You can appear to be overdisciplined, overachieving and very strict with yourself. You may experience mental and physical restlessness and your thoughts move faster than your actions. Large amounts of tension may lead to feelings of helplessness, constant cramping and the inability to relax. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, or denial of intuition. This can be seen in children that were/are expected to get along in an adult world or when a child is raised with non age-appropriate correctness and discipline. Signs of long term stress and tension may include fibromyalgia, spasms, grinding or clenching of teeth, and stiffness. Guidance: Be kind to yourself. Find ways to relax and release tension (perhaps through a hobby or moderate physical exertion or yoga). Positive Affirmation: I easily relax and let go of tension, renewing my strength daily.',
  },
  24: {
    name: 'Uneasiness',
    subtitle: 'Chakra 6 — Third Eye Conflict',
    description: 'Emotional issues addressed: Constant tension and chronic stress lead to feelings of discomfort, uneasiness, muscular tension and chronic pain. You feel like you cannot relax and your body and mind has fallen out of harmony. You lack joy in your life, feel a mental disconnect, may experience feelings of depression and helplessness, and perhaps want to escape from your life responsibilities. You may feel the inability to be at ease or satisfied with yourself. You long to see and experience the beautiful things in life. This conflict can be due to not being allowed to establish one\'s own identity, being in an unsafe environment, or denial of intuition. There may be this deep feeling of being unloved or undeserving of love. This is the "flight" version of adrenal collapse. Chronic stress, chronic tension, and chronic pain prevail with disruptive negative thoughts reflecting feelings of discontent, disconnection, hopelessness and depression. Guidance: Listen for the needs and wishes within yourself, and fulfill them including rest, relaxation, being loved, pampered and cared for. Positive Affirmation: I respect my body and listen to my needs, continuing my path of healing.',
  },
  25: {
    name: 'Distrust',
    subtitle: 'Chakra 7 — Crown Chakra Conflict',
    description: 'Emotional issues addressed: You appear optimistic on the outside, but have a deep underlying feeling that things are not going to work out. You are skeptical and do not trust others easily. You want proof before you will believe, you question everything. Past disappointments have left you hurt and opening up emotionally or asking for help makes you feel vulnerable. You are more comfortable figuring things out on your own. You do not trust your inner voice or intuition. This conflict can be due to forced religion, blind obedience, withheld information and lies. There is fear to open oneself up or ask for help from others, due to possibly being manipulated, stolen from, taken advantage of or harmed. There is a resistance to listen to one\'s inner voice and trust the overall plan in life. Guidance: The simplest formula to overcome distrust is to first trust yourself. Trusting yourself and listening to your inner voice is an act of self love, self confidence and self respect. Positive Affirmation: I know my goals and I am confident that I am guided in the right direction.',
  },
  26: {
    name: 'Materialistic',
    subtitle: 'Chakra 7 — Crown Chakra Conflict',
    description: 'Emotional issues addressed: You feel you have had to fight hard to achieve your goals in life. Nothing comes easy. You work hard for what you have, and your possessions are important to you. You desire to have things (i.e., property, jewelry, knowledge, spiritual values, good deeds, successful career) and like the status that comes with it. It may be hard to give away your things. There may be a fear of major change, with comfort in things staying the same. This conflict can be due to forced religion, blind obedience, withheld information and lies. Due to life circumstances, there is a feeling of constant battle, life is a struggle, always have to fight for survival or nothing comes easily, and the attitude of "I believe in what I can see" develops. A focus on possessions means missing out on the essence of life. Guidance: Life is greater than the possessions that we have. Rediscover the many modest pleasures and inner joys that you have been overlooking in your life. Positive Affirmation: I am grateful for what I have and use my resources wisely on my journey through life.',
  },
  27: {
    name: 'Not Wanting to Face Reality',
    subtitle: 'Chakra 7 — Crown Chakra Conflict',
    description: 'Emotional issues addressed: You view life through rose-colored glasses and ignore the uglier sides of life. You feel the world is a hard place, so you seek escapism (i.e., dreams, fantasy, books, meditation, or drugs). You are not able to tolerate your reality, so you banish it from your perception. You may dream of living a different life. Often you are more open to perceptions, but unable to integrate your visions into everyday life. This conflict can be due to forced religion, blind obedience, withheld information and lies. Behind the escape tendencies and repression can be hidden emotional traumas or unbearable frustrations that are associated with dark or unpleasant memories. This can lead to avoiding reality or escapism tendencies including retreating to a world of fantasy, psychoses or drug addiction. Guidance: Truthfulness and objectivity are qualities that correlate with your existence and living in the present. Escaping from past painful events cuts you off from your own liveliness. You are not able to change the past by pretending to be in a different reality, so focus on the present. Positive Affirmation: I view my personal reality with open eyes, while remaining in the present and keeping my mind on my goals.',
  },
  28: {
    name: 'Strong Beliefs',
    subtitle: 'Chakra 7 — Crown Chakra Conflict',
    description: 'Emotional issues addressed: You have deep convictions and strong beliefs that you hold very close to your heart. You feel certain rules and order are necessary when dealing with life (family, religion, work, the world). At times, you are unwilling to deviate from your opinion, even if there are disadvantages and limitations. Your standards or ideals may be too fixed or set too high, which leads to frustration when things are not accomplished or others do not live up to your expectations. This conflict can be due to forced religion, blind obedience, withheld information and lies. One may have been told how the world has to function and how they are to function within it. They are often locked in a belief pattern that no longer applies, are rigid people and may have arthritic symptoms. Guidance: You must first appreciate yourself and attend to your needs in order to align your convictions, beliefs, rules, ideals and standards with what is realistic. Acknowledge more realistic expectations from others. Positive Affirmation: I orient my thoughts, actions and trust to a higher wisdom.',
  },
};

// ── ACUTE REMEDIES ──────────────────────────────────────────────────────────

export const ACUTE_REMEDY_DESCRIPTIONS = {
  Geovita: 'Geovita is used in cases of exposure to geopathic stress and electrosmog. Symptoms can include: sleep disorders, difficulty falling asleep, nightmares, abnormal exhaustion, feeling worn out, tired upon rising in the morning, chronic fatigue syndrome, fibromyalgia, rheumatic pain and joint issues, arrhythmias, migraines or tension headaches, learning difficulties (especially in children — ADD, ADHD), infertility, frequent miscarriages, hormonal disorders, and all cancers. Standard dosage: 2 drops, 3 times per day.',
  Anxiovita: 'Anxiovita is used in cases of anxiety and nervous tension. It works to prevent anxiety and provide immediate relief during acute states of anxiety and/or panic attacks. It can be used to prevent anxiety before exposure to stressful situations such as examinations, speeches, the dentist, flying and social gatherings. Symptoms and conditions include: tachycardia, sweating, tightness in the chest, fatigue, exhaustion, nervousness, tension, stress and chronic pain. Standard dosage: 2 drops, 3 times per day.',
  Neurovita: 'Neurovita is used in cases of stress, nervous tension and pain. It is useful for those who are unable to relax and often hold tension and stress in the body, leading to pain. Symptoms and conditions can include: fatigue, burnout, chronic pain, headaches, neck tension, back pain, neuralgia (nerve pain), restlessness, MS, stroke, post-traumatic conditions and other nerve conditions. Standard dosage: 2 drops, 3 times per day.',
  Paravita: 'Paravita is used in cases of hypofunction of the parasympathetic nervous system. It is often needed for those who feel exhausted, are unable to recuperate even though they get enough rest or sleep, and after long periods of struggle and mental and/or physical stress. Symptoms and conditions include: fatigue, exhaustion, adrenal fatigue, feeling overtaxed, hypothyroidism, sluggishness, constipation, cramps of the inner organs (gallbladder, bladder and intestines), asthma, migraine, eczema, and low blood pressure. Standard dosage: 2 drops, 3 times per day.',
  Simvita: 'Simvita is used in cases of hyperfunction of the sympathetic nervous system. It is useful for nervous tension and the inability to relax. Symptoms and conditions include: hyperthyroidism, high blood pressure, cardiac arrhythmia (tachycardia), tension, jitteriness, sleeplessness, restlessness, diarrhea, sweating, trembling and headache. Standard dosage: 2 drops, 3 times per day.',
};
