apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJaMmwwYkdGaUsyUmxjR3h2ZVMxMGIydGxiaTB5TURjNU5UQXdPakptV1ZaRFFTMVVXalIwVVdSMFFXVjJiemxPIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-secret
  namespace: api
type: kubernetes.io/dockerconfigjson
